### ISSUE TITLE
Compare with S2

### ISSUE THREAD

**Issue by ppKrauss** [tammoippen/geohash-hilbert#3]
Hi, a suggestion, 

Try to compare performance and grid behaviour with [s2sphere](https://pypi.org/project/s2sphere/) or other Python interface for [s2geometry](https://github.com/google/s2geometry), that also use Hilbert curve to [global grid indexation](https://en.wikipedia.org/wiki/Discrete_Global_Grid).

**Comment by tammoippen** [comment]
Hi @ppKrauss,

Sorry for the long wait. I would welcome such a comparison, but currently this is out of scope for me. If you are interested in writing such a comparison, i will link it in the README!

Best,
Tammo
